DROP TYPE IF EXISTS grocery;
CREATE TYPE grocery AS ENUM (
    'Main',
    'Snack',
    'Lunch',
    'Breakfast'
);

CREATE TABLE IF NOT EXISTS shopping_list (
    id INTEGER primary key generated by default as identity,
    name text not null,
    price decimal(12, 2) not null,
    date_added TIMESTAMP default now() not null,
    checked boolean default false not null,
    category grocery not null
);