create table if not exists blogful_articles (
    id INTEGER primary key generated by default as identity,
    title text not null,
    date_published TIMESTAMPTZ default now() not null,
    content text
);

